{% set name = "gradsflow" %}
{% set version = "0.0.8.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 318108865894f98ce7e6d975529ea7754912b874870eb4f88f3283102d23a115

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.2,<4
  run:
    - python >=3.7
    - accelerate >=0.5.0
    - loguru >=0.5
    - ray-default >=1.6.0
    - ray-tune >=1.6.0
    - rich
    - smart_open >=5.1
    - timm
    - pytorch >=1.4
    - torchvision
    - torchmetrics >=0.6.0
    - wandb >=0.12.9
    - tensorboard

test:
  imports:
    - gradsflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gradsflow/gradsflow
  summary: An open-source AutoML Library based on PyTorch
  license: Apache-2.0
  license_file: LICENSE
  description: |
    GradsFlow is an open-source AutoML Library based on PyTorch. Our goal 
    is to democratize AI and make it available to everyone.

    It can automatically build & train Deep Learning Models for different 
    tasks on your laptop or to a remote cluster directly from your laptop. 
    It provides a powerful and easy-to-extend Model Training API that can 
    be used to train almost any PyTorch model. Though GradsFlow has its 
    own Model Training API it also supports PyTorch Lightning Flash to 
    provide more rich features across different tasks.

    PyPI: [https://pypi.org/project/gradsflow/](https://pypi.org/project/gradsflow/)

  doc_url: https://docs.gradsflow.com/
  dev_url: https://github.com/gradsflow/gradsflow

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainer(s) from Package Repo
    - aniketmaurya
