{% set name = "gradsflow" %}
{% set version = "0.0.8.dev0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b24f834ba9b71878ae09c20a8512d10bfcf9245365d42e3b8b9ae5bf6b7db0cb

build:
  number: 0
  noarch: python
  script:
    # TODO: remove when issue gets fixed
    # - removing "tests/" folder from {{ name }} downloaded tar.gz
    # - the following lines (rm -rf tests/) and (rmdir -r tests/)
    #   will not be necessary once the issue gradsflow/gradsflow#140 
    #   has been closed.
    #
    # - https://github.com/gradsflow/gradsflow/issues/140
    - echo -e "\n>>>  REMOVING tests/ folder from {{ name }}...  <<<\n"
    - rm -rf tests/  # [not win]
    - rmdir -r tests/  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - accelerate >=0.5.0
    - loguru >=0.5    
    - ray-default >=1.6.0
    - ray-tune >=1.6.0
    - rich
    - smart_open >=5.1    
    - timm
    - pytorch >=1.4
    - torchvision
    - torchmetrics >=0.5.0

test:
  imports:
    - gradsflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gradsflow/gradsflow
  summary: An open-source AutoML Library based on PyTorch
  license: Apache-2.0
  license_file: LICENSE
  description: |
    GradsFlow is an open-source AutoML Library based on PyTorch. Our goal 
    is to democratize AI and make it available to everyone.

    It can automatically build & train Deep Learning Models for different 
    tasks on your laptop or to a remote cluster directly from your laptop. 
    It provides a powerful and easy-to-extend Model Training API that can 
    be used to train almost any PyTorch model. Though GradsFlow has its 
    own Model Training API it also supports PyTorch Lightning Flash to 
    provide more rich features across different tasks.
  doc_url: https://docs.gradsflow.com/
  dev_url: https://github.com/gradsflow/gradsflow

extra:
  recipe-maintainers:
    - aniketmaurya
    - sugatoray
